In [91]:
'''
求梯度
'''
import torch
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(a.is_leaf)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * 8) / (a - 5)
print(b.is_leaf)
print(b.requires_grad)
print(b)

True
False
True
False
True
tensor([[ -2.0000,  -5.3333],
        [-12.0000, -32.0000]], grad_fn=<DivBackward0>)


In [92]:
z = torch.tensor([[1.0, 0.1], [0.01, 0.001]], dtype=torch.float)
b.backward(z)
print(a.grad)


tensor([[-2.5000, -0.4444],
        [-0.1000, -0.0400]])


In [93]:
x = torch.tensor(1.0, requires_grad=True)
y1 = x ** 2
with torch.no_grad():
    y2 = x ** 3
y3 = y1 + y2
print(x.requires_grad)
print(y1, y1.requires_grad)
print(y2, y2.requires_grad)
print(y3, y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [94]:
y3.backward()
print(x.grad)

tensor(2.)


In [95]:
x = torch.ones(1, requires_grad=True)
print(x.data)
print(x.data.requires_grad)

tensor([1.])
False


In [96]:
y = 2 * x
x.data *= 100
y.backward()
print(x)
print(x.grad)

tensor([100.], requires_grad=True)
tensor([2.])
