In [15]:
'''
线性回归：简洁版本
'''

import torch
import numpy as np

# 生成数据集
num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.tensor(np.random.normal(0, 1, (num_examples, num_inputs)), dtype=torch.float)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.tensor(np.random.normal(0, 0.01, size=labels.size()), dtype=torch.float)

In [16]:
# 读取数据
import torch.utils.data as Data
batch_size = 10
# 将训练数据的特征和标签组合
dataset = Data.TensorDataset(features, labels)
# 随机读取小批量
data_iter = Data.DataLoader(dataset, batch_size,shuffle=True)

import torch.nn as nn
net = nn.Sequential()
net.add_module('linear', nn.Linear(num_inputs, 1))

In [17]:
# 定义模型
net = nn.Sequential()
net.add_module('linear', nn.Linear(num_inputs, 1))

In [18]:
# 初始化模型参数
from torch.nn import init
init.normal_(net[0].weight, mean=0, std=0.01)
init.constant_(net[0].bias, val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [19]:
# 定义损失函数
loss = nn.MSELoss()


In [21]:
# 定义优化算法
import torch.optim as optim
optimizer = optim.SGD(net.parameters(), lr=0.03) # SGD算法
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [22]:
# 训练模型
num_epochs = 3
for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        output = net(X)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad() # 梯度清零，等价于net.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d, loss: %f' % (epoch, l.item()))


epoch 1, loss: 0.000196
epoch 2, loss: 0.000065
epoch 3, loss: 0.000180


In [23]:
dense = net[0]
print(true_w, dense.weight)
print(true_b, dense.bias)

[2, -3.4] Parameter containing:
tensor([[ 2.0000, -3.4000]], requires_grad=True)
4.2 Parameter containing:
tensor([4.1995], requires_grad=True)
