In [4]:
'''
torch基础语法
'''
import torch
import numpy
# torch创建
x = torch.randn(5, 3)
print(x)
y = torch.rand(5, 3)
# torch的形状
print(y.size())
print(y.shape)
print(y)
# 加法的表示形式： 四种
print(x + y)
print(torch.add(x, y))

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

y.add_(x)
print(y)

tensor([[ 0.5570,  1.1372, -0.8584],
        [ 0.5830, -0.2161,  0.2341],
        [-0.3955,  1.7814,  0.4831],
        [-0.7377, -2.1611, -0.5787],
        [-0.2872,  0.8691,  1.2738]])
torch.Size([5, 3])
torch.Size([5, 3])
tensor([[0.6721, 0.6937, 0.9878],
        [0.7342, 0.9997, 0.8603],
        [0.6252, 0.6797, 0.5926],
        [0.6243, 0.7581, 0.3048],
        [0.4615, 0.4275, 0.5854]])
tensor([[ 1.2291,  1.8310,  0.1295],
        [ 1.3172,  0.7836,  1.0944],
        [ 0.2298,  2.4611,  1.0757],
        [-0.1134, -1.4029, -0.2738],
        [ 0.1743,  1.2965,  1.8593]])
tensor([[ 1.2291,  1.8310,  0.1295],
        [ 1.3172,  0.7836,  1.0944],
        [ 0.2298,  2.4611,  1.0757],
        [-0.1134, -1.4029, -0.2738],
        [ 0.1743,  1.2965,  1.8593]])
tensor([[ 1.2291,  1.8310,  0.1295],
        [ 1.3172,  0.7836,  1.0944],
        [ 0.2298,  2.4611,  1.0757],
        [-0.1134, -1.4029, -0.2738],
        [ 0.1743,  1.2965,  1.8593]])
tensor([[ 1.2291,  1.8310,  0.1295],
        [ 

In [5]:
# copy torch => copy出来的跟原数组共享内存
b = torch.empty(5, 3)
b.copy_(y)
print(b)
# 若想要不共享内存 用clone
y_cp = y.clone()
y_cp += 1
print(y_cp)
print(y)

tensor([[ 1.2291,  1.8310,  0.1295],
        [ 1.3172,  0.7836,  1.0944],
        [ 0.2298,  2.4611,  1.0757],
        [-0.1134, -1.4029, -0.2738],
        [ 0.1743,  1.2965,  1.8593]])
tensor([[ 2.2291,  2.8310,  1.1295],
        [ 2.3172,  1.7836,  2.0944],
        [ 1.2298,  3.4611,  2.0757],
        [ 0.8866, -0.4029,  0.7262],
        [ 1.1743,  2.2965,  2.8593]])
tensor([[ 1.2291,  1.8310,  0.1295],
        [ 1.3172,  0.7836,  1.0944],
        [ 0.2298,  2.4611,  1.0757],
        [-0.1134, -1.4029, -0.2738],
        [ 0.1743,  1.2965,  1.8593]])


In [6]:
# item()函数 将torch转换为python number
# 并且only one element tensors can be converted to Python scalars
i = torch.rand(1)
print(i, i.item())

tensor([0.3530]) 0.3530401587486267


In [7]:
# 矩阵转置
print(x)
print(x.T)


tensor([[ 0.5570,  1.1372, -0.8584],
        [ 0.5830, -0.2161,  0.2341],
        [-0.3955,  1.7814,  0.4831],
        [-0.7377, -2.1611, -0.5787],
        [-0.2872,  0.8691,  1.2738]])
tensor([[ 0.5570,  0.5830, -0.3955, -0.7377, -0.2872],
        [ 1.1372, -0.2161,  1.7814, -2.1611,  0.8691],
        [-0.8584,  0.2341,  0.4831, -0.5787,  1.2738]])


In [8]:
# 索引出来的结果与原数据共享内存 修改一个，另一个也会改变
y = x[0, :]
print(x[0, :])
y += 1
print(y)
print(x[0, :])


tensor([ 0.5570,  1.1372, -0.8584])
tensor([1.5570, 2.1372, 0.1416])
tensor([1.5570, 2.1372, 0.1416])


In [9]:
x = torch.rand(5, 3)
y = x.view(15)
print(x.size(), y.size())
print(x[0, 0], y[0])

torch.Size([5, 3]) torch.Size([15])
tensor(0.1893) tensor(0.1893)


In [10]:
# 广播机制
x = torch.arange(1, 3).view(1, 2)
print(x)
y = torch.arange(1, 4).view(3, 1)
print(y)
print(x + y)


tensor([[1, 2]])
tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [14]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = x + y
print(id_before == id(y))

True


In [15]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [21]:
a = numpy.ones(5)
b = torch.from_numpy(a)
print(a, b)
a += 1
print(a, b)
b += 1
print(a, b)

c = torch.tensor(a)
a += 1
print(a, c)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [24]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))
else:
    print("none")

none


In [47]:
x = torch.ones(2, 2, requires_grad=True)
print(x)
print(x.grad_fn)
y = x + 2
print(y)
print(y.grad_fn)
print(x.is_leaf, y.is_leaf)

z = y * y * 3
out = z.mean()
print(z, out)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
True False
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [79]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad) # False
a.requires_grad_(True)
print(a.requires_grad)
print("a leaf: ", a.is_leaf)
# b = torch.randn(2, 2)
b = (a * 3)
b.requires_grad_(True)
print("b leaf: ", b.is_leaf)
print(b.requires_grad)

c = a + 1
print("c leaf: ", c.is_leaf)
print("c grad: ", c.requires_grad)

False
True
a leaf:  True
b leaf:  False
True
c leaf:  False
c grad:  True


In [75]:
c = a + b
print(c.is_leaf)
print(c.grad_fn)
print(c)
c = c.sum()
c.backward()
print("a: ", a.grad)
print("b: ", b.grad)

print(id(a), id(b))

False
tensor([[  1.3433,  21.6519],
        [-29.7750,  26.9980]], grad_fn=<AddBackward0>)
a:  tensor([[4., 4.],
        [4., 4.]])
b:  None
2315863586176 2315865712000


<ipython-input-75-bdd13eb4d42d>:8: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  print("b: ", b.grad)


tensor([[ 6.0892,  6.2531],
        [ 0.3503, -0.2356]])